api:
  base_url: "https://api.github.com"
  rate_limit_pause: 60  # seconds to wait when rate limited
  timeout: 30
  activity_limit: 30  # Number of days of user activity to fetch

scraper:
  max_repos: 10
  topics: ["python", "javascript", "machine-learning"]
  # Stars config is now optional. You can:
  # 1. Specify both min and max:
  stars:
   min: 100
   max: 500
  # 2. Specify only min:
  #stars:
  #  min: 100
  # 3. Specify only max:
  #stars:
  #  max: 500
  # 4. Remove stars section entirely for no limits

output:
  format: "json"
  path: "data/repos"
