api:
  base_url: "https://api.github.com"
  rate_limit_pause: 60  # seconds to wait when rate limited
  timeout: 30
  activity_limit: 30  # Number of days of user activity to fetch

scraper:
  max_repos: 5
  topics: ["swift", "ios"]
  # Stars config is now optional. You can:
  # 1. Specify both min and max:
  stars:
   min: 100
   max: 500
  # 2. Specify only min:
  #stars:
  #  min: 100
  # 3. Specify only max:
  #stars:
  #  max: 500
  # 4. Remove stars section entirely for no limits

  # Push date filter settings
  push_date_filter:
    enabled: true
    type: "days"  # can be "days" or "date"
    days: 30  # Only include repos pushed within last 30 days
    # date: "2024-01-01"  # Or use specific date (YYYY-MM-DD format)

  # Documentation quality filter settings
  doc_filter:
    enabled: true
    # Add score threshold config
    score_threshold:
      enabled: true
      min: 50  # Only include repos with score >= 50
      max: null  # Include any score up to max (set null for no upper limit)
    min_readme_words: 200  # Minimum words in README to be considered well-documented
    min_code_comment_ratio: 5  # Minimum percentage of comments to code
    require_docs_folder: true  # Require docs/ folder or equivalent
    docs_folder_patterns:  # Folder names that count as documentation
      - "docs"
      - "documentation" 
      - "doc"
      - "wiki"
    markdown_scoring:
      enabled: true
      weight: 5  # Points to award for markdown file presence
      min_files: 2  # Minimum files for full points
      quality_checks:
        enabled: false  # Set to true to enable markdown quality checks -- will significantly slow down scraping
        grammar_weight: 10  # Points for grammar checking
        max_grammar_errors: 10  # Max grammar errors before 0 points

output:
  format: "html"  # Change to "html" to generate HTML report
  path: "data/repos"
